import { mkdir, mkdtemp, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  EXPECTED_SPEC_VERSION,
  EXPECTED_SPREADSHEET_ID,
  GENERATED_SPEC_FILES,
  MANIFEST_PATH,
  REPO_ROOT,
  SNAPSHOT_PATH,
  SPEC_SYNC_OWNED_FILES,
} from "./config.mjs";
import { assertSpec } from "./errors.mjs";
import { getSpecCatalog, validateCanonicalSnapshot } from "./schema.mjs";
import { hashGeneratedContent, parseIdList, sourceFingerprint } from "./lib.mjs";

function markdownCell(value) {
  return String(value ?? "").replaceAll("|", "\\|").replaceAll("\n", "<br>");
}

function table(records, columns) {
  const headings = columns.map(([heading]) => heading);
  const keys = columns.map(([, key]) => key);
  const rows = records.map((record) => keys.map((key) => markdownCell(record[key])));
  return [headings, headings.map(() => "---"), ...rows].map((row) => `| ${row.join(" | ")} |`).join("\n");
}

function containsAny(record, expression) {
  return expression.test(record.values.join("\n"));
}

function selectDocumentRows(catalog, kind) {
  const predicate = kind === "content-management"
    ? /教材|コンテンツ|データ|Qualification|Syllabus|Domain|Topic|Concept|Question/u
    : /教材|AI|AWS|source|取得|正規化|Content pipeline|Concept|Question/iu;
  const req = new Set(catalog.reqRows.filter((row) => containsAny(row, predicate)).map((row) => row.ID));
  const bas = new Set(catalog.basRows.filter((row) => containsAny(row, predicate) || parseIdList(row["関連要件"], "REQ").some((id) => req.has(id))).map((row) => row.ID));
  for (const row of catalog.basRows) if (bas.has(row.ID)) for (const id of parseIdList(row["関連要件"], "REQ")) req.add(id);
  const det = new Set(catalog.detRows.filter((row) => containsAny(row, predicate) || parseIdList(row["関連基本設計"], "BAS").some((id) => bas.has(id))).map((row) => row.ID));
  for (const row of catalog.detRows) if (det.has(row.ID)) for (const id of parseIdList(row["関連基本設計"], "BAS")) bas.add(id);
  return {
    reqRows: catalog.reqRows.filter((row) => req.has(row.ID)),
    basRows: catalog.basRows.filter((row) => bas.has(row.ID)),
    detRows: catalog.detRows.filter((row) => det.has(row.ID)),
  };
}

function buildDevelopmentRules(catalog, fingerprint) {
  return `<!-- GENERATED by pnpm run spec:sync. Do not edit directly. -->
# 開発・保守仕様

- spec_version: \`${EXPECTED_SPEC_VERSION}\`
- source_fingerprint: \`${fingerprint}\`
- 承認元: Google Sheet（\`${EXPECTED_SPREADSHEET_ID}\`）

以下は承認Sheetの全REQ/BAS/DET行を、意味を変更せず表形式へ同期したものです。

## 要件定義

${table(catalog.reqRows, [["ID", "ID"], ["分類", "分類"], ["要件", "要件"], ["目的・理由", "目的・理由"], ["優先度", "優先度"], ["状態", "状態"]])}

## 基本設計

${table(catalog.basRows, [["ID", "ID"], ["領域", "領域"], ["基本設計", "基本設計"], ["主な画面/機能", "主な画面/機能"], ["関連要件", "関連要件"], ["設計判断", "設計判断"], ["状態", "状態"]])}

## 詳細設計

${table(catalog.detRows, [["ID", "ID"], ["対象", "対象"], ["詳細仕様", "詳細仕様"], ["入力", "入力"], ["処理", "処理"], ["出力/保存", "出力/保存"], ["関連基本設計", "関連基本設計"], ["状態", "状態"]])}
`;
}

function buildIndex(catalog, contentManagement, contentPipeline, fingerprint) {
  const allIds = [...catalog.reqIds, ...catalog.basIds, ...catalog.detIds, ...catalog.chkIds];
  const ids = (selection) => [...selection.reqRows, ...selection.basRows, ...selection.detRows].map((row) => row.ID).join(", ");
  return `<!-- GENERATED by pnpm run spec:sync. Do not edit directly. -->
# プロダクト仕様索引

承認マスターはGoogle Sheetです。repo内仕様はCodex向け同期物であり、直接変更しません。

- spec_version: \`${EXPECTED_SPEC_VERSION}\`
- source_fingerprint: \`${fingerprint}\`

## 現在同期済み

- [開発・保守仕様](development-rules.md) — ${allIds.join(", ")}
- [コンテンツ管理仕様](content-management.md) — ${ids(contentManagement)}
- [教材ソース取得・正規化仕様](content-pipeline.md) — ${ids(contentPipeline)}

## 機能別仕様の予定領域

onboarding / diagnosis / study-session / study-task / mastery / review / mock-exam / learning-skills / graduation / content-management

未同期領域は、対応する承認済みtaskで必要になった時点で追加します。
`;
}

function buildFocusedSpec(title, description, selection, fingerprint) {
  return `<!-- GENERATED by pnpm run spec:sync. Do not edit directly. -->
# ${title}

- spec_version: \`${EXPECTED_SPEC_VERSION}\`
- source_fingerprint: \`${fingerprint}\`
- 承認元: Google Sheet（\`${EXPECTED_SPREADSHEET_ID}\`）

${description}

## 要件定義

${table(selection.reqRows, [["ID", "ID"], ["分類", "分類"], ["要件", "要件"], ["目的・理由", "目的・理由"], ["状態", "状態"]])}

## 基本設計

${table(selection.basRows, [["ID", "ID"], ["領域", "領域"], ["基本設計", "基本設計"], ["主な画面/機能", "主な画面/機能"], ["関連要件", "関連要件"], ["設計判断", "設計判断"], ["状態", "状態"]])}

## 詳細設計

${table(selection.detRows, [["ID", "ID"], ["対象", "対象"], ["詳細仕様", "詳細仕様"], ["入力", "入力"], ["処理", "処理"], ["出力/保存", "出力/保存"], ["関連基本設計", "関連基本設計"], ["状態", "状態"]])}
`;
}

function buildSourceTraceability(catalog) {
  const requirements = catalog.reqRows.map((requirement) => {
    const basIds = catalog.basRows.filter((basic) => parseIdList(basic["関連要件"], "REQ").includes(requirement.ID)).map((basic) => basic.ID);
    const detIds = catalog.detRows.filter((detail) => parseIdList(detail["関連基本設計"], "BAS").some((id) => basIds.includes(id))).map((detail) => detail.ID);
    const chkIds = catalog.chkRows.filter((check) => parseIdList(check["要件定義"], "REQ").includes(requirement.ID)).map((check) => check["論点ID"]);
    return { req_id: requirement.ID, bas_ids: basIds, det_ids: detIds, chk_ids: chkIds, product_spec: "docs/product-specs/development-rules.md" };
  });
  const checks = catalog.chkRows.map((check) => ({
    chk_id: check["論点ID"],
    req_ids: parseIdList(check["要件定義"], "REQ"),
    bas_ids: parseIdList(check["基本設計"], "BAS"),
    det_ids: parseIdList(check["詳細設計"], "DET"),
  }));
  return {
    spec_version: EXPECTED_SPEC_VERSION,
    all_spec_ids: [...catalog.reqIds, ...catalog.basIds, ...catalog.detIds, ...catalog.chkIds],
    source_relationships: { requirements, checks },
    implementation_mapping: "scripts/spec/implementation-traceability.json",
    note: "Source relationships are generated only from the approved Sheet. Code/test mappings are maintained and verified separately.",
  };
}

export function renderGeneratedFiles(snapshot) {
  validateCanonicalSnapshot(snapshot);
  const fingerprint = sourceFingerprint(snapshot);
  const catalog = getSpecCatalog(snapshot);
  const contentManagement = selectDocumentRows(catalog, "content-management");
  const contentPipeline = selectDocumentRows(catalog, "content-pipeline");
  return new Map([
    ["docs/product-specs/index.md", buildIndex(catalog, contentManagement, contentPipeline, fingerprint)],
    ["docs/product-specs/development-rules.md", buildDevelopmentRules(catalog, fingerprint)],
    ["docs/product-specs/content-management.md", buildFocusedSpec("コンテンツ管理仕様", "資格・シラバス・学習範囲コンテンツに関係する承認済み仕様です。", contentManagement, fingerprint)],
    ["docs/product-specs/content-pipeline.md", buildFocusedSpec("教材ソース取得・正規化仕様", "教材取得・正規化・AI handoff境界に関係する承認済み仕様です。", contentPipeline, fingerprint)],
    ["docs/traceability.yaml", `${JSON.stringify(buildSourceTraceability(catalog), null, 2)}\n`],
  ]);
}

export function assertGeneratedFileSet(actualFiles) {
  assertSpec(
    JSON.stringify(actualFiles) === JSON.stringify(GENERATED_SPEC_FILES),
    "SPEC_GENERATED_FILES_SET_INVALID",
    "manifest.generated_files",
    GENERATED_SPEC_FILES.join(","),
    (actualFiles ?? []).join(","),
  );
}

async function readIfExists(target) {
  try {
    return await readFile(target, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

function normalized(content) {
  return content?.replace(/\r\n?/g, "\n");
}

async function transactionalWrite(repoRoot, entries, beforePromote) {
  if (entries.length === 0) return;
  const transactionRoot = await mkdtemp(path.join(repoRoot, ".spec-sync-transaction-"));
  const stagedRoot = path.join(transactionRoot, "staged");
  const backupRoot = path.join(transactionRoot, "backup");
  const promoted = [];
  let cleanupTransaction = true;
  try {
    for (const [relativePath, content] of entries) {
      const staged = path.join(stagedRoot, relativePath);
      await mkdir(path.dirname(staged), { recursive: true });
      await writeFile(staged, content, "utf8");
      assertSpec(
        normalized(await readFile(staged, "utf8")) === normalized(content),
        "SPEC_TRANSACTION_STAGE_INVALID",
        relativePath,
        "staged content matches",
        "staged content differs",
      );
    }

    for (const [index, [relativePath]] of entries.entries()) {
      if (beforePromote) await beforePromote({ relativePath, index });
      const target = path.join(repoRoot, relativePath);
      const staged = path.join(stagedRoot, relativePath);
      const backup = path.join(backupRoot, relativePath);
      await mkdir(path.dirname(target), { recursive: true });
      const hadExisting = await readIfExists(target) !== null;
      if (hadExisting) {
        await mkdir(path.dirname(backup), { recursive: true });
        await rename(target, backup);
      }
      try {
        await rename(staged, target);
      } catch (error) {
        if (hadExisting) await rename(backup, target);
        throw error;
      }
      promoted.push({ target, backup, hadExisting });
    }
  } catch (error) {
    const rollbackErrors = [];
    for (const entry of promoted.reverse()) {
      try {
        await rm(entry.target, { force: true });
        if (entry.hadExisting) await rename(entry.backup, entry.target);
      } catch (rollbackError) {
        rollbackErrors.push(rollbackError);
      }
    }
    if (rollbackErrors.length > 0) {
      cleanupTransaction = false;
      throw new AggregateError([error, ...rollbackErrors], `SPEC_TRANSACTION_ROLLBACK_FAILED: recovery files preserved at ${transactionRoot}`);
    }
    throw error;
  } finally {
    if (cleanupTransaction) await rm(transactionRoot, { recursive: true, force: true });
  }
}

export async function synchronizeSnapshot(snapshot, {
  repoRoot = REPO_ROOT,
  writeSnapshot = false,
  generatedAt = () => new Date().toISOString(),
  beforePromote,
} = {}) {
  validateCanonicalSnapshot(snapshot);
  const files = renderGeneratedFiles(snapshot);
  assertGeneratedFileSet([...files.keys()]);
  const fingerprint = sourceFingerprint(snapshot);
  const generatedFilesHash = hashGeneratedContent(files);
  const existingManifestText = await readIfExists(path.join(repoRoot, MANIFEST_PATH));
  let existingManifest = null;
  try {
    existingManifest = existingManifestText ? JSON.parse(existingManifestText) : null;
  } catch {
    existingManifest = null;
  }
  const generatedContentMatches = (await Promise.all([...files].map(async ([relativePath, content]) => {
    const existing = await readIfExists(path.join(repoRoot, relativePath));
    return normalized(existing) === normalized(content);
  }))).every(Boolean);
  const snapshotContent = `${JSON.stringify(snapshot, null, 2)}\n`;
  const snapshotMatches = !writeSnapshot || normalized(await readIfExists(path.join(repoRoot, SNAPSHOT_PATH))) === normalized(snapshotContent);
  const manifestCoreMatches = existingManifest
    && existingManifest.spec_version === EXPECTED_SPEC_VERSION
    && existingManifest.source_spreadsheet_id === EXPECTED_SPREADSHEET_ID
    && existingManifest.source_fingerprint === fingerprint
    && existingManifest.generated_files_hash === generatedFilesHash
    && JSON.stringify(existingManifest.generated_files) === JSON.stringify(GENERATED_SPEC_FILES);
  if (generatedContentMatches && snapshotMatches && manifestCoreMatches) {
    return { changed: false, fingerprint, generatedFilesHash, changedFiles: [] };
  }

  const pendingFiles = new Map();
  if (writeSnapshot && !snapshotMatches) pendingFiles.set(SNAPSHOT_PATH, snapshotContent);
  for (const [relativePath, content] of files) {
    const target = path.join(repoRoot, relativePath);
    const existing = await readIfExists(target);
    if (normalized(existing) !== normalized(content)) {
      assertSpec(SPEC_SYNC_OWNED_FILES.includes(relativePath), "SPEC_SYNC_PATH_FORBIDDEN", relativePath, "spec-owned file", "not owned");
      pendingFiles.set(relativePath, content);
    }
  }
  const preserveGeneratedAt = existingManifest
    && existingManifest.source_fingerprint === fingerprint
    && existingManifest.generated_files_hash === generatedFilesHash
    && existingManifest.generated_at;
  const manifest = {
    spec_version: EXPECTED_SPEC_VERSION,
    source_spreadsheet_id: EXPECTED_SPREADSHEET_ID,
    source_fingerprint: fingerprint,
    generated_at: preserveGeneratedAt || generatedAt(),
    generated_files_hash: generatedFilesHash,
    generated_files: GENERATED_SPEC_FILES,
  };
  const manifestContent = `${JSON.stringify(manifest, null, 2)}\n`;
  if (normalized(existingManifestText) !== normalized(manifestContent)) pendingFiles.set(MANIFEST_PATH, manifestContent);
  for (const relativePath of pendingFiles.keys()) {
    assertSpec(SPEC_SYNC_OWNED_FILES.includes(relativePath), "SPEC_SYNC_PATH_FORBIDDEN", relativePath, "spec-owned file", "not owned");
  }
  const changedFiles = [...pendingFiles.keys()];
  await transactionalWrite(repoRoot, [...pendingFiles], beforePromote);
  return { changed: changedFiles.length > 0, fingerprint, generatedFilesHash, changedFiles };
}
